version: "3"

tasks:
  setup-venv:
    desc: Setup virtualenv
    cmds:
      - rm -rf .venv
      - POETRY_NO_INTERACTION=1
        POETRY_VIRTUALENVS_CREATE=1
        POETRY_VIRTUALENVS_IN_PROJECT=1
        VENV_PATH=.venv
        poetry install
      - echo "source .venv/bin/activate"

  run:
    desc: Run app
    cmds:
      - ./.venv/bin/python3 -m uvicorn main:app --reload
