version: "3"

tasks:
  download-llama2-code:
    desc: Download llama2 code
    cmds:
      - |
        GIT_HASH=0b871f1
        rm -rf llama.cpp
        git clone https://github.com/ggerganov/llama.cpp.git
        cd llama.cpp
        git checkout ${GIT_HASH}
        make

  download-llama2-model:
    desc: Download llama2 model
    cmds:
      - |
        export MODEL=llama-2-13b-chat.ggmlv3.q4_0.bin
        if [ ! -f llama.cpp/models/${MODEL} ]; then
            curl -L "https://huggingface.co/TheBloke/Llama-2-13B-chat-GGML/resolve/main/${MODEL}" -o llama.cpp/models/${MODEL}
        fi
        ./convert-llama-ggml-to-gguf.py --eps 1e-5 -i ./llama.cpp/models/llama-2-13b-chat.ggmlv3.q4_0.bin -o ./llama.cpp/models/llama-2-13b-chat.ggmlv3.q4_0.gguf.bin

  run-llama2:
    desc: Run llama2
    cmds:
      - ./main -m ./models/llama-2-13b-chat.ggmlv3.q4_0.gguf.bin -p "What is the day today?"
